name: Check Do Not Merge

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - review_requested
      - labeled
      - unlabeled

permissions: read-all

jobs:
  fail-for-do-not-merge:
    if: contains(github.event.pull_request.labels.*.name, 'do not merge')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is labeled do not merge
        run: |
          echo "::notice::Merging permission is diabled for PRs when the `do not merge` label is applied."

          if [ "${{ contains(github.event.pull_request.labels.*.name, 'do not merge') }}" = "true" ]; then
            echo "::error::Pull request is labeled as `do not merge`. Please remove the label before merging."
            exit 1
          else
            exit 0
          fi
