name: Check Do Not Merge

on:
  pull_request:
    branches: [ $default-branch ]
    types:
      - opened
      - labeled
      - unlabeled

permissions: read-all

jobs:
  fail-for-do-not-merge:
    if: contains(github.event.pull_request.labels.*.name, 'do not merge')
    runs-on: ubuntu-latest
    steps:
      - name: Fail if do not merge label is applied
        run: |
          echo "Cannot merge with `do not merge` label applied."
          exit 1
